
- name: armbian-orangepi_zero2_2w-bookworm
  type: armbian
  img_download_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi_zero2w_bookworm.img.xz"
  img_hash_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi_zero2w_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 5000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-opi-zero2w
  rpi_json:
    name: "MainsailOS $VERSION$ - Orange Pi Zero2W (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "opizero2w-64bit"
